enableGlobalCache: true

nodeLinker: pnp

packageExtensions:
  babel-plugin-relay@*:
    dependencies:
      "@babel/runtime": ^7.21.5

pnpEnableEsmLoader: true

yarnPath: .yarn/releases/yarn-4.0.0-rc.43.cjs
